name: localhost-customhity
version: '${version}'

main: pl.localhost.customhity.Main
api-version: '1.20'
load: POSTWORLD

authors: [ Localhost ]
website:
  discord: localhost_127001


commands:
  customhity:

permissions:
  customhity.admin:
    default: op